### ISSUE TITLE
New Parenthesis Rule for exceptions, gives error

### ISSUE THREAD

**Issue by lordofwizard** [LeobardoArguelles/cbz-merger#2]
```
❯ python merge.py ~/Documents/Mangas/Monster/ -a ./Monster.cbz
Traceback (most recent call last):
  File "/tmp/cbz-merger/merge.py", line 4, in <module>
    import cli.app
  File "/home/lordofwizard/venv/lib/python3.10/site-packages/cli/app.py", line 242
    except Exception, e:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
```

**Comment by LeobardoArguelles** [comment]
Hi! Thanks for bringing this to my attention. I'll take a look and fix it.

**Comment by LeobardoArguelles** [comment]
I located the source of the issue: the problem occurs inside pyCLI, which appears to no longer be maintained (the [last version](https://pypi.org/project/pyCLI/#history) is from 2012!

I'll have to drop pyCLI in favor of some up-to-date library. 

For now, a quick and dirty fix would be to:
1. Install Python 3.8
2. Create a virtual environment using Python3.8 (something like `python3.8 -m venv venv`, the exact syntaxis may depend on your system)
3. Activate the virtual environment `source venv/bin/activate`
4. Install the requirements `pip install -r requirements.txt`

Python3.8 does not throw any errors. 

Since this is a workaround, I'll keep the issue open until I update my code to replace pyCLI.
